select * from flights
where day_id = $1;
select * from lodging
where day_id = $1;
select * from restaurants
where day_id = $1;
select * from activities
where day_id = $1;
select * from rental_cars
where day_id = $1;